[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Extensions.bcmath",
  "php82Extensions.gd",
  "php82Extensions.tokenizer",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl",
  "composer"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan config:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
